name: "CI/CD Pipeline: Format, Test and Deploy"

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest
          pip install -r requirements.txt

      - name: Format code with Black
        run: |
          black .
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Format code with Black" || true
          git push origin
      
      - name: Run tests
        env:
          BASE_S3_LAMBDA_API_GATEWAY_URL: ${{ secrets.BASE_S3_LAMBDA_API_GATEWAY_URL }}
          BUCKET_NAME_REV_SEARCH_DATABASE_IMAGES: ${{ secrets.BUCKET_NAME_REV_SEARCH_DATABASE_IMAGES }}
        run: |
          pytest 

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          email: ${{ secrets.HEROKU_EMAIL_ID }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # Dockerfile directory.
          dockerfile_directory: ./

          # Dockerfile name.
          dockerfile_name: Dockerfile

          # Additional options of docker build command.
          docker_options: "--no-cache"

          # (Optional, default: "web")
          # Select the process type for which you want the docker container to be uploaded.
          # By default, this argument is set to "web".
          # For more information look at https://devcenter.heroku.com/articles/process-model
          process_type: web
          